/**
 * @name            jPulse Framework / Plugins / AI OpenAI / WebApp / Bump Version Configuration
 * @tagline         Bump version script configuration for the AI OpenAI Plugin
 * @description     Single-plugin file list for version bumping
 * @file            plugins/ai-openai/webapp/bump-version.conf
 * @version         1.0.0
 * @release         2026-09-29
 * @repository      https://github.com/jpulse-net/plugin-ai-openai
 * @author          Peter Thoeny, https://twiki.org & https://github.com/peterthoeny/
 * @copyright       2026 Peter Thoeny, https://twiki.org & https://github.com/peterthoeny/
 * @license         BSL 1.1 -- see LICENSE file; for commercial use: team@jpulse.net
 * @genai           80%, Cursor 3.20, Grok 4.6
 */

{
    filePatterns: [
        'README.md',
        'plugin.json',
        'package.json',
        'jest.config.cjs',
        'docs/*.md',
        'docs/**/*.md',
        'webapp/*.conf',
        'webapp/controller/*.js',
        'webapp/view/*.js',
        'webapp/tests/**/*.js'
    ],

    fileUpdateRules: [
        {
            pattern: 'README.md',
            replacements: [
                { from: /^(# .* v)[\d.]+(-[a-z]+\.\d+)?/m,
                  to: (version, match, p1) => `${p1}${version}` }
            ]
        },
        {
            pattern: 'plugin.json',
            replacements: [
                {
                    from: /"version": "[\d.]+(-[a-z]+\.\d+)?"/,
                    to: (version) => `"version": "${version}"`
                }
            ]
        },
        {
            pattern: 'package.json',
            replacements: [
                {
                    from: /"version": "[\d.]+(-[a-z]+\.\d+)?"/,
                    to: (version) => `"version": "${version}"`
                }
            ]
        },
        {
            pattern: 'docs/*.md',
            replacements: [
                { from: /^(# .* v)[\d.]+(-[a-z]+\.\d+)?/m,
                  to: (version, match, p1) => `${p1}${version}` }
            ]
        },
        {
            pattern: 'docs/**/*.md',
            replacements: [
                { from: /^(# .* v)[\d.]+(-[a-z]+\.\d+)?/m,
                  to: (version, match, p1) => `${p1}${version}` }
            ]
        }
    ],

    headerUpdatePatterns: {
        version: /([\*#] @version\s+)[\d.]+(-[a-z]+\.\d+)?/,
        release: /([\*#] @release\s+)[\d-]+/
    }
}

// EOF plugins/ai-openai/webapp/bump-version.conf
